### Цена книги по названию из БД, конвертация из BLR -> RUB, USD, EUR, за несколько дат
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB,USD,EUR

###
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB,USD
Accept: application/json

### Цена книги в валюте, курс валюты берётся за количество дней указанных в dayCount
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB,USD,EUR?dayCount=5