### Цена книги по названию из БД, конвертация из BLR -> RUB, USD, EUR, за несколько дат
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB,USD,EUR
Accept: image/svg+xml
### Цена книги в валюте, курс валюты берётся за количество дней указанных в dayCount
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB?dayCount=5
Accept: text/csv
###
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB?dayCount=5
Accept: application/pdf
###
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB?dayCount=5
Accept: application/json
###
GET http://localhost:8080/api/v1/book/price/stat/Harry Potter/RUB?dayCount=5
Accept: image/svg+xml

